# .trab
language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build" # master 브랜치에 푸시 되었을 때 수행되는 명령어

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - mhoh@miridih.com
  #slack: miridih:63vC2SIecsMGvyJAjijHRhU2

# deploy 명령어가 실행되기 전에 수행된다.
# AWS CodeDeploy는 Jar 파일을 인식하지 못하기 때문에 Jar 파일과 설정 파일들을 모아 압축해야한다.
before_deploy:
  - zip -r springboot-webservice * # 프로젝트명
  - mkdir -p deploy # Travis CI가 실행중인 위치에 deploy 디렉토리 생성
  - mv springboot-webservice.zip deploy/springboot-webservice.zip # 압축한 zip 파일을 deploy 디렉토리로 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: miristudy-ci-cd # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # 여기서 지정한 디렉토리 위치의 파일들만 S3로 전송
    wait-until-deployed: true